spring.datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://172.16.16.142:3306/db_shop_store?serverTimezone=UTC
  data-username: test
  data-password: test

spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: update